### ISSUE TITLE
How to add Vault connector in Anypoint Studio Mule pallette

### ISSUE THREAD

**Issue by fogboundturtle** [avioconsulting/mule-vault-connector#1]
I am new to anypoint studio. I was asked to look at integration between hashicorp and mulesoft. I am unable to add the vault connector in my anypoint studio mule palette. Can you help me with some step by step instruction ?

Thanks.

**Comment by adammead** [comment]
Hi @fogboundturtle, here are the steps for getting it added locally. I'll add these to the README too, but I wanted to get you going as soon as possible.

1. Clone this project locally
2. Execute `mvn install` from repository base directory (containing the pom.xml) to install the connector into your local maven repository, it will compile and run tests in test containers, so you need docker locally too. Alternatively, you can run `mvn install -Dmaven.test.skip=true` to skip those tests.
3. Add the dependency below to your pom.xml:
```xml
<dependency>
    <groupId>f2ea2cb4-c600-4bb5-88e8-e952ff5591ee</groupId>
    <artifactId>vault-connector</artifactId>
    <version>0.2.0</version>
    <classifier>mule-plugin</classifier>
</dependency>
```
4. After saving the pom.xml, Anypoint Studio will load the connector in the palette

**Comment by fogboundturtle** [comment]
I am using the embedded maven of Anypoint studio 7.4 on Windows. I don't have MVN install on my PC. Do I need to get Maven install separately ?

**Comment by adammead** [comment]
Yes, you need to install maven separately to build and install the connector.

**Comment by fogboundturtle** [comment]
Thank you for your help.  I got it to work.

**Comment by fogboundturtle** [comment]
I am getting a lot of Java warning with your vault connector and I don't see any connection to my local hashicorp vault

![image](https://user-images.githubusercontent.com/63123397/78594960-06efd180-77fe-11ea-9155-ffca1e4e1e5e.png)

**Comment by adammead** [comment]
What does your Vault Config look like under Global Configurations?

**Comment by fogboundturtle** [comment]
![image](https://user-images.githubusercontent.com/63123397/78598428-27bb2580-7804-11ea-9b9b-c3029da55a7e.png)

this is running my local hashicorp server. I am running in -dev mode v1.
When I compile the application

[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running com.avioconsulting.mule.connector.vault.provider.VaultEc2IDDocAuthTestCase
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.697 s <<< FAILURE! - in com.avioconsulting.mule.connector.vault.provider.VaultEc2IDDocAuthTestCase
[ERROR] initializationError(com.avioconsulting.mule.connector.vault.provider.VaultEc2IDDocAuthTestCase)  Time elapsed: 0.005 s  <<< ERROR!
java.lang.IllegalArgumentException: pom file doesn't exits for path: E:\AnypointStudio\studio-workspace\Vault%20Connector\pom.xml

[INFO] Running com.avioconsulting.mule.connector.vault.provider.VaultEc2MetaDataAuthenticationTestCase
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.001 s <<< FAILURE! - in com.avioconsulting.mule.connector.vault.provider.VaultEc2MetaDataAuthenticationTestCase
[ERROR] initializationError(com.avioconsulting.mule.connector.vault.provider.VaultEc2MetaDataAuthenticationTestCase)  Time elapsed: 0 s  <<< ERROR!
java.lang.IllegalArgumentException: pom file doesn't exits for path: E:\AnypointStudio\studio-workspace\Vault%20Connector\pom.xml

[INFO] Running com.avioconsulting.mule.connector.vault.provider.VaultIamAuthTestCase
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0 s <<< FAILURE! - in com.avioconsulting.mule.connector.vault.provider.VaultIamAuthTestCase
[ERROR] initializationError(com.avioconsulting.mule.connector.vault.provider.VaultIamAuthTestCase)  Time elapsed: 0 s  <<< ERROR!
java.lang.IllegalArgumentException: pom file doesn't exits for path: E:\AnypointStudio\studio-workspace\Vault%20Connector\pom.xml

[INFO] Running com.avioconsulting.mule.connector.vault.provider.VaultOperationsTestCase
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0 s <<< FAILURE! - in com.avioconsulting.mule.connector.vault.provider.VaultOperationsTestCase
[ERROR] initializationError(com.avioconsulting.mule.connector.vault.provider.VaultOperationsTestCase)  Time elapsed: 0 s  <<< ERROR!
java.lang.IllegalArgumentException: pom file doesn't exits for path: E:\AnypointStudio\studio-workspace\Vault%20Connector\pom.xml

[INFO] Running com.avioconsulting.mule.connector.vault.provider.VaultSSLConnectionTestCase
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0 s <<< FAILURE! - in com.avioconsulting.mule.connector.vault.provider.VaultSSLConnectionTestCase
[ERROR] initializationError(com.avioconsulting.mule.connector.vault.provider.VaultSSLConnectionTestCase)  Time elapsed: 0 s  <<< ERROR!
java.lang.IllegalArgumentException: pom file doesn't exits for path: E:\AnypointStudio\studio-workspace\Vault%20Connector\pom.xml

**Comment by adammead** [comment]
Anypoint Studio is trying to compile the connector code while building your Mule project. Close the connector project in studio and it should build properly.

**Comment by fogboundturtle** [comment]
Alright.  This is good now. Thanks again for you support.
